pycon_multitenant/notes/urls.py
from django.urls import path

from . import views


app_name = 'notes'

urlpatterns = [
    path('create/', views.NoteCreateView.as_view(), name='create')
]

pycon_multitenant/tenants/urls.py
from django.urls import path

from . import views


app_name = 'tenants'

urlpatterns = [
    path('create/', views.TenantCreateView.as_view(), name='create')
]

pycon_multitenant/notes/models.py
from django.db import models


class Note(models.Model):
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)

pycon_multitenant/tenants/models.py
from django.db import models
from tenant_schemas.models import TenantMixin


class Tenant(TenantMixin):
    name = models.CharField(max_length=100)

pycon_multitenant/tenants/forms.py
from django import forms

from tenants.models import Tenant


class TenantCreateForm(forms.ModelForm):
    subdomain = forms.CharField(max_length=100, required=True)

    class Meta:
        model = Tenant
        fields = ['name', 'subdomain']

    def save(self, commit=True):
        instance = super().save(commit=False)
        subdomain = self.cleaned_data.get('subdomain')
        instance.schema_name = subdomain.replace('-', '_')
        # You need to replace localhost for your domain
        instance.domain_url = f'{subdomain}.localhost'
        instance.save()
        return instance

pycon_multitenant/notes/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from .models import Note


class NotesHome(TemplateView):
    template_name = 'notes/notes_home.html'

    def get_context_data(self):
        context = super().get_context_data()
        context['notes'] = Note.objects.all()
        return context


class NoteCreateView(CreateView):
    model = Note
    fields = ['content']
    template_name = 'notes/note_form.html'
    success_url = reverse_lazy('home')

pycon_multitenant/tenants/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from .models import Tenant
from .forms import TenantCreateForm


class TenantsHome(TemplateView):
    template_name = 'tenants/tenants_home.html'

    def get_context_data(self):
        context = super().get_context_data()
        context['tenants'] = Tenant.objects.exclude(schema_name='public')
        return context


class TenantCreateView(CreateView):
    form_class = TenantCreateForm
    model = Tenant
    template_name = 'tenants/tenant_form.html'
    success_url = reverse_lazy('home')

pycon_multitenant/templates/_menu.html
<!-- We can use the tenant in the request to ask for the specific tenant we are in -->
{% if request.tenant.schema_name == 'public' %}
    <li {% if request.path == '/' %} class="active" {% endif %}>
        <a href="{% url 'home' %}">
            <i class="fa fa-bookmark"></i> <span class="nav-label">Home</span>
        </a>
    </li>
    <li {% if "/tenants/create/" in request.path %} class="active" {% endif %}>
        <a href="{% url 'tenants:create' %}">
            <i class="fa fa-database"></i> <span class="nav-label">Create Tenant</span>
        </a>
    </li>
{% else %}
    <li {% if request.path == '/' %} class="active" {% endif %}>
        <a href="{% url 'home' %}">
            <i class="fa fa-bookmark"></i> <span class="nav-label">Home</span>
        </a>
    </li>
    <li {% if "/notes/create/" in request.path %} class="active" {% endif %}>
        <a href="{% url 'notes:create' %}">
            <i class="fa fa-file-text-o"></i> <span class="nav-label">Create Note</span>
        </a>
    </li>
{% endif %}

pycon_multitenant/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block page_title %} {% endblock page_title %}</title>
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom_style.css' %}" rel="stylesheet">

    {{ form.media }}

    {% block css %}
    {% endblock css %}

</head>

<body>

<div id="wrapper">

    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav" id="side-menu">
                <li class="nav-header">
                    <span id="tenant-name" class="clear">
                        <span class="block m-t-xs"> <strong class="font-bold">{{ request.tenant.name | upper }}</strong> </span>
                    </span>
                    <div class="logo-element">
                        IN+
                    </div>
                </li>

                {% include '_menu.html' %}
            </ul>

        </div>
    </nav>

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">

                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="http://localhost:8000">
                            <i class="fa fa-sign-out"></i> Go to Public Tenant
                        </a>
                    </li>
                </ul>

            </nav>
        </div>

        <div class="wrapper wrapper-content animated fadeInRight">

            {% block content %}

                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>{% block panel_title %}{% endblock panel_title%}</h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">

                            {% block panel_content %}
                            {% endblock panel_content %}

                        </div>
                    </div>
                </div>

            {% endblock content %}

        </div>
        <div class="footer">
            <div>
                <strong>Copyright</strong> Pycon Colombia &copy; 2018
            </div>
        </div>

    </div>
</div>

<!-- Mainly scripts -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static 'js/inspinia.js' %}"></script>
<script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>


{% block js %}
{% endblock js %}

</body>

</html>

pycon_multitenant/templates/notes/note_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block page_title %}
    Create a Note
{% endblock page_title %}

{% block panel_title %}
    Create a Note
{% endblock panel_title %}

{% block panel_content %}
    <form action="" method="POST" class="form-horizontal" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row">
            {% bootstrap_form form layout="horizontal" %}

            <center>{% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}</center>
        </div>

    </form>
{% endblock panel_content %}

pycon_multitenant/templates/notes/notes_home.html
{% extends 'base.html' %}

{% block page_title %}
    Your notes
{% endblock page_title %}


{% block content %}
    <div class="row">
        {% for note in notes %}
            <div class="col-lg-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <h3><i class="fa fa-file-text-o"></i> {{ note.content }}</h3>
                        <small>Created at: {{ note.created_at }}</small>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <h3>Please add some notes...</h3>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

pycon_multitenant/templates/tenants/tenant_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block page_title %}
    Create Tenant
{% endblock page_title %}

{% block panel_title %}
    Create Tenant
{% endblock panel_title %}

{% block panel_content %}
    <form action="" method="POST" class="form-horizontal" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row">
            {% bootstrap_form form layout="horizontal" %}

            <center>{% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}</center>
        </div>

    </form>
{% endblock panel_content %}

pycon_multitenant/templates/tenants/tenants_home.html
{% extends 'base.html' %}

{% block page_title %}
    Home
{% endblock page_title %}


{% block content %}
    <div class="row">
        {% for tenant in tenants %}
            <div class="col-lg-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>{{ tenant.name }}</h5>
                    </div>
                    <div class="ibox-content">
                        <a href="http://{{ tenant.domain_url }}:8000" class="btn btn-primary">Go In!</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <h3>Please create some tenants...</h3>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}